parameters:
    database_driver:    pdo_mysql
    database_host:      localhost
    database_name:      alom_dev
    database_name_test: alom_test
    database_user:      root
    database_password:
    mailer_user:        contact@alexandre-salome.fr
    mailer_password:    xxxxxxxxxxx
    comment_mail:       alexandre.salome@gmail.com
    rss_token:          rsstoken
    secret:             xxxxxxxxxx
    yui_compiler_path: /var/java/yuicompressor-2.4.6.jar
